# Generated by Django 4.1.4 on 2022-12-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hackathon_participantant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
