# Generated by Django 4.1.4 on 2022-12-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_hackathon_participantant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hackathon_participantant',
            new_name='hackathon_participant',
        ),
    ]
